### ISSUE TITLE
Non standard admin url

### ISSUE THREAD

**Issue by mrnebbi** [billythekid/ezmap#1]
Hello Mr Billy!

I am having issue with your plugin. Admin URL is not working when not /admin
Send help.

~Manuel~ MrNebbi

**Comment by billythekid** [comment]
Sake, I knew when I was writing it that that url it was wrong. Stupid craft
3 docs.

I’ll fix that tomorrow (or feel free to PR), cheers Ian.

**Comment by mrnebbi** [comment]
Leave it with me ;)

**Comment by billythekid** [comment]
fixed in #94decc8
