### ISSUE TITLE
Fix Composer 2 compatibility

### ISSUE THREAD

**Issue by brandonkelly** [billythekid/ezmap#2]
When installing this plugin with Composer 1, the following deprecation notice is output:

> Deprecation Notice: Class `billythekid\ezmap\assetbundles\EZMap\EZMapAsset` located in `./vendor/billythekid/ezmap/src/assetbundles/ezmap/EZMapAsset.php` does not comply with psr-4 autoloading standard\. It will not autoload anymore in Composer v2\.0\.

Composer 2 was released on October 24, and is now the default version that will be installed, so it’s critical that this gets resolved ASAP, or people will start getting `Class not found` errors.

To fix, run the following command:

```bash
> git mv src/assetbundles/ezmap src/assetbundles/EZMap
```

Then commit your change and [tag a new release](https://craftcms.com/docs/3.x/extend/plugin-store.html#plugin-releases).

_(Note that you must use the `git mv` command, as Git tends to not notice case-sensitive file renames otherwise.)_

**Comment by billythekid** [comment]
oh wow how am i only just seeing this!

Sorry Brandon, will fix asap. I actually don't think the assetbundle is used in this plugin, a throwback to pluginfactory scaffolding I think. I can probably get rid completely. I know I fixed a few others in the run up to this in the way you suggested.

Cheers for the issue!

**Comment by brandonkelly** [comment]
Hah… thanks for releasing the fix! Looks like the Plugin Store is unable to pick it up, however, because we’ve lost our connection to the repo. Can you please log into https://id.craftcms.com and reconnect your GitHub account?
